### ISSUE TITLE
app push 外連網頁(滿意度問卷)

### ISSUE THREAD

**Issue by monkiequeen** [abc873693/GDG-DevFest-App#24]
1. app push 可外連 google form 做活動結束後的滿意度問卷調查
2. 有條件可判斷+鎖定高雄場的參加者 push 嗎？可以精準的話最好
from Queenie

**Comment by weitsai** [comment]
> 2.有條件可判斷+鎖定高雄場的參加者 push 嗎？可以精準的話最好

應該沒有辦法，下載 App 的人我們沒有辦法判斷他是不是要來高雄，如果真的要其實應該是從 KKTIX 去發。

**Comment by abc873693** [comment]
以實現於v0.0.7 版本中
可透過 推播加上連結實現
